eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8082/eureka

server:
  port: 8083
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: products
          uri: http://localhost:8085
          predicates:
            - Path=/products/**
        - id: shopping
          uri: http://localhost:8086
          predicates:
            - Path=/shopping/**
management:
  tracing:
    sampling:
      probability: 1.0
